# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Comment.create!([
  { :comment => "this is a comment and its about a doi", :doi_id => 2, :user_id => 2, :created_at => "2013-11-01 03:19:35", :updated_at => "2013-11-01 03:19:35" }
])



Doi.create!([
  { :label => "Google.com", :description => "google", :user_id => 1, :created_at => "2013-10-31 21:28:26", :updated_at => "2013-10-31 21:28:26" },
  { :label => "doi-test", :description => "this doi was created in seeds.rb", :user_id => 2, :created_at => "2013-11-01 03:19:34", :updated_at => "2013-11-01 03:19:34" }
])



Url.create!([
  { :datetime_added => "2013-10-31 21:28:26", :doi_id => 1, :created_at => "2013-10-31 21:28:26", :updated_at => "2013-10-31 21:28:26", :url_text => "google.com" },
  { :datetime_added => nil, :doi_id => 2, :created_at => "2013-11-01 03:19:34", :updated_at => "2013-11-01 03:19:34", :url_text => "http://www.google.com" }
])



User.create!([
  { :email => "oulrich@mail.csuchico.edu", :encrypted_password => "$2a$10$2bRJ6R6e.4F3vk1r/g9QfOYsrshApjrWoUH/p1PPctr/XWH9Yksyy", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 1, :current_sign_in_at => "2013-10-31 21:28:13", :last_sign_in_at => "2013-10-31 21:28:13", :current_sign_in_ip => "132.241.73.45", :last_sign_in_ip => "132.241.73.45", :created_at => "2013-10-31 21:28:13", :updated_at => "2013-10-31 21:28:13" },
  { :email => "o2@g.com", :encrypted_password => "$2a$10$9CtbDch2aUXkHscQlBMrwe6Av4F71wQ0ZFO/M.IwHuRG6pvIeF/U.", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 1, :current_sign_in_at => nil, :last_sign_in_at => nil, :current_sign_in_ip => nil, :last_sign_in_ip => nil, :created_at => "2013-11-01 03:19:34", :updated_at => "2013-11-01 03:19:34" }
])


